src/debate_website/debate/api/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
# debate.api.views
from .views import (
	PostListAPIView,
	PostDetailAPIView,
	PostUpdateAPIView,
	PostDeleteAPIView,
	)


urlpatterns = [
    url(r'^posts/$',PostListAPIView.as_view(),name='post-list'),
    url(r'^posts/(?P<pk>\d+)$',PostDetailAPIView.as_view(),name='post-detail'),
    url(r'^posts/(?P<pk>\d+)/update/$',PostUpdateAPIView.as_view(),name='post-update'),
    url(r'^posts/(?P<pk>\d+)/delete/$',PostDeleteAPIView.as_view(),name='post-delete'),
]

src/debate_website/debate/urls.py
from django.conf.urls import url,include
from . import views



app_name='debate'

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^my_posts/(?P<pk>[0-9]+)$', views.my_posts,name='my_posts'),
    url(r'^categories/(?P<pk>[0-9]+)$', views.categories,name='categories'),
    url(r'^posts/(?P<pk>[0-9]+)$', views.detail,name='detail'),
   	url(r'^posts/create/$',views.CreatePost,name='post-create'),
   	url(r'^posts/(?P<pk>[0-9]+)/update/$',views.UpdatePost.as_view(),name='post-update'),
   	url(r'^posts/(?P<pk>[0-9]+)/delete/$',views.DeletePost,name='post-delete'),

    url(r'^categories/create/$',views.CreateCategory,name='category-create'),
    url(r'^categories/(?P<pk>[0-9]+)/delete/$',views.DeleteCategory,name='category-delete'),

    url(r'^posts/(?P<pk>[0-9]+)/comment/(?P<com_id>[0-9]+)$',views.delete_comment,name='delete-comment'),
    url(r'^like/$',views.like_post,name='like_post'),


   	url(r'^register/$',views.UserFormView.as_view(),name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

]

src/debate_website/debate_website/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]


from django.contrib import admin
from django.conf.urls import url,include
# from django.urls import path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^debate/admin/',admin.site.urls),
    url(r'^debate/',include('debate.urls')),
    url(r'^api/debate/',include(("debate.api.urls","debate.api"),namespace='debate-api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/debate_website/debate/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django import utils



class Category(models.Model):
	name=models.CharField(verbose_name=u"Category",max_length=50,unique=True)

	def __str__(self):
		return "Category ---> "+str(self.name)

class Post(models.Model):

	post_category=models.ForeignKey(Category,on_delete=models.CASCADE)
	post_owner=models.ForeignKey(User,verbose_name=u"Owner",on_delete=models.CASCADE)
	post_topic=models.CharField(max_length=250)
	post_content=models.TextField(max_length=1000)
	post_date=models.DateTimeField(auto_now_add=True)
	post_likes=models.ManyToManyField(User,related_name="likes",blank=True)

	def get_absolute_url(self):
		return reverse('debate:detail',kwargs={'pk' : self.id})
	def __str__(self):
		return str(self.post_category)+"--->"+str(self.post_owner)+"--->"+str(self.post_topic)

	@property
	def total_likes(self):
		return self.post_likes.count()

class Comment(models.Model):
	comment_name=models.ForeignKey(User,verbose_name=u"Owner",on_delete=models.CASCADE)
	comment_post=models.ForeignKey(Post,verbose_name=u'Topic',on_delete=models.CASCADE)
	comment_text=models.TextField(max_length=1000)
	comment_time=models.DateTimeField(default=utils.timezone.now)
	parent=models.ForeignKey("self",null=True,blank=True,on_delete=models.CASCADE,related_name="replies")

	def __str__(self):
		return str(self.id)+'-'+str(self.comment_name) + ' - ' + str(self.comment_text)

	def children(self):
		return Comment.objects.filter(parent=self)

	def all(self):
		return Comment.objects.filter(parent=None).order_by('-comment_time')

	@property
	def is_parent(self):
		if self.parent is not None:
			return False
		return True

src/debate_website/debate/forms.py
from django.contrib.auth.models import User
from .models import Category,Post,Comment
from django import forms
from django.contrib.auth import get_user_model
import datetime
from crispy_forms.helper import FormHelper
from django.forms.fields import DateField


User=get_user_model()

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)
	class Meta: #info about your class is metaclass
		model=User
		fields=['username','email','first_name','last_name','password']

class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields='__all__'


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		# fields='__all__'
		fields=['post_category','post_topic','post_content']#,'post_likes']


class CommentForm(forms.ModelForm):
	comment_text=forms.CharField(label="",max_length=1000,widget= forms.Textarea(attrs={'placeholder':'Add new comment','rows':1, 'cols':100}))

	class Meta:
		model=Comment
		fields=['comment_text']

src/debate_website/debate/api/views.py
from rest_framework.generics import (
	ListAPIView,
	RetrieveAPIView,
	UpdateAPIView,
	DestroyAPIView
	)

from debate.models import Post
from .serializers import PostListSerializer,PostDetailSerializer


# http://127.0.0.1:8000/api/debate/?format=json #for json format

class PostListAPIView(ListAPIView):
	queryset=Post.objects.all()
	serializer_class=PostListSerializer


class PostDetailAPIView(RetrieveAPIView):
	queryset=Post.objects.all()
	serializer_class=PostDetailSerializer

class PostUpdateAPIView(UpdateAPIView):
	queryset=Post.objects.all()
	serializer_class=PostDetailSerializer

class PostDeleteAPIView(DestroyAPIView):
	queryset=Post.objects.all()
	serializer_class=PostDetailSerializer

src/debate_website/debate/views.py
from django.shortcuts import render
from .models import Category,Post,Comment
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from .forms import UserForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.contrib import messages
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin,PermissionRequiredMixin
from .forms import UserForm,PostForm,CategoryForm,CommentForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect




class UserFormView(View):
	form_class=UserForm
	template_name='debate/registration_form.html'


	def get(self,request):
		all_categories=Category.objects.all()
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form,'all_categories':all_categories})

	def post(self,request):
		all_categories=Category.objects.all()

		form=self.form_class(request.POST)

		if form.is_valid():
			user= form.save(commit=False) #not yet saved in DB due to commit=False

			username=form.cleaned_data['username']	#if username is email for logging in
			password=form.cleaned_data['password']
			user.set_password(password)
			user.save()


			user= authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request,user)
					return redirect('debate:index')
				else:
					return render(request, 'debate/index.html', {'all_posts': Post.objects.order_by('post_date'), 'all_categories':all_categories})
			else:
				messages.error(request,"Invalid Login")
				return redirect("debate:register")

		return render(request,self.template_name,{'form':form,'all_categories':all_categories})

def login_user(request):
	all_categories=Category.objects.all()
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				all_posts = Post.objects.order_by('post_date')
				if 'next' in request.POST:
					return redirect(request.POST.get('next'))
				else:
					return redirect('debate:index')
			else:
				messages.error(request,"Your account has been disabled")
				return redirect("debate:login_user")
		else:
			messages.error(request,"Invalid Login")
			return redirect("debate:login_user")
	return render(request, 'debate/login.html', {'all_categories':all_categories})

def logout_user(request):
	logout(request)
	form = UserForm(request.POST or None)
	context = {
		"form": form,
	}
	return redirect('debate:login_user')


def index(request):
	all_categories=Category.objects.all()
	all_posts=Post.objects.all()
	query = request.GET.get("q")
	if query:
		all_posts = all_posts.filter(
			Q(post_topic__icontains=query)
			| Q(post_category__name__icontains=query)
			| Q(post_owner__username__icontains=query)
		).distinct()
		print ("query_all_posts:",all_posts)
		print ("query_all_posts :",all_posts == None)
		print ("all_posts.count() :",all_posts.count())
		if all_posts.count()!=0:
			print ("all_posts :",all_posts)
			print ("all_posts is available")
			return render(request, 'debate/index.html', {'all_categories':all_categories,'all_posts': all_posts})
		else:
			messages.error(request,"No Post found for %s."%query)
			return redirect("debate:index")
	else:
		return render(request, 'debate/index.html', {'all_categories':all_categories,'all_posts': all_posts.order_by('-id')})

def my_posts(request,pk):
	all_categories=Category.objects.all()
	all_posts=Post.objects.filter(post_owner=pk)
	print("all_posts :",all_posts)
	query = request.GET.get("q")
	if query:
		all_posts = all_posts.filter(
			Q(post_topic__icontains=query)
			| Q(post_category__name__icontains=query)
			| Q(post_owner__username__icontains=query)
		).distinct()
		print ("query_all_posts:",all_posts)
		print ("query_all_posts :",all_posts == None)
		print ("all_posts.count() :",all_posts.count())
		if all_posts.count()!=0:
			print ("all_posts :",all_posts)
			print ("all_posts is available")
			return render(request, 'debate/index.html', {'all_categories':all_categories,'all_posts': all_posts})
		else:
			messages.error(request,"No Post found for %s."%query)
			return redirect("debate:index")
	else:
		return render(request, 'debate/index.html', {'all_categories':all_categories,'all_posts': all_posts.order_by('post_date')})

def categories(request,pk):
	all_categories=Category.objects.all()
	all_posts=Post.objects.filter(post_category=pk)
	print("all_posts :",all_posts)
	query = request.GET.get("q")
	if query:
		all_posts = all_posts.filter(
			Q(post_topic__icontains=query)
			| Q(post_category__name__icontains=query)
			| Q(post_owner__username__icontains=query)
		).distinct()
		print ("query_all_posts:",all_posts)
		print ("query_all_posts :",all_posts == None)
		print ("all_posts.count() :",all_posts.count())
		if all_posts.count()!=0:
			print ("all_posts :",all_posts)
			print ("all_posts is available")
			return render(request, 'debate/index.html', {'all_categories':all_categories,'all_posts': all_posts})
		else:
			messages.error(request,"No Post found for %s."%query)
			return redirect("debate:index")
	else:
		return render(request, 'debate/index.html', {'all_categories':all_categories,'all_posts': all_posts.order_by('post_date')})


def detail(request,pk):
	all_categories=Category.objects.all()
	posts=get_object_or_404(Post,id=pk)
	print("all_posts :",posts)
	print("dir(posts) :",dir(posts))
	all_comments=Comment.objects.filter(comment_post=pk,parent=None).order_by('-comment_time')
	print("all_comments :",all_comments)
	is_liked=False
	if posts.post_likes.filter(id=request.user.id).exists():
		is_liked=True
	query = request.GET.get("q")
	print ("request.method :",request.method)
	if request.method=='POST':
		print("POST FORM")

		if request.user.is_authenticated:
			form = CommentForm(request.POST or None)
			if form.is_valid():
				print("valid")
				comment = form.save(commit=False)
				comment.comment_text=request.POST.get('comment_text')
				comment.parent_id=request.POST.get('parent_id')
				comment_text=request.POST.get('comment_text')
				parent_qs=None
				try:
					parent_id=int(request.POST.get("parent_id"))
				except:
					parent_id=None
				if parent_id:
					parent_qs=Comment.objects.get(id=parent_id)
				comment=Comment.objects.create(comment_name=request.user,comment_post=posts,comment_text=comment.comment_text,parent=parent_qs)
				comment.save()
				return redirect('debate:detail',pk=pk)
		else:
			messages.error(request,"Login to comment")
			form=CommentForm()
	else:
		form=CommentForm()
		print("GET FORM")

	context={
				'posts': posts,
				'pk':pk,
				'is_liked':is_liked,
				'total_likes':posts.total_likes,
				'all_categories':all_categories,
				'all_comments':all_comments,
				'form':form,
			}

	return render(request, 'debate/detail.html', context)
	
@login_required(login_url='debate:login_user')
def CreateCategory(request):
	all_categories=Category.objects.all()
	form = CategoryForm(request.POST or None)
	if request.user.is_superuser:
		if form.is_valid():
			category = form.save(commit=False)
			category.save()
			return redirect("debate:index")
	else:
		messages.error(request,"User must me admin to add category")
	context = {
		"form": form,'all_categories':all_categories
	}
	return render(request, 'debate/post_form.html', context)


@login_required(login_url='debate:login_user')
def DeleteCategory(request,pk):
	category=Category.objects.get(id=pk)
	if request.user.is_superuser:
		category.delete()
		messages.success(request,str(category.name)+ " category deleted successfully")
		return redirect('debate:index')
	else:
		messages.error(request,"User must be admin to delete a category")
		return redirect('debate:index')

@login_required(login_url='debate:login_user')
def CreatePost(request):
	all_categories=Category.objects.all()
	form = PostForm(request.POST or None)#, request.FILES or None)

	if form.is_valid():
		post = form.save(commit=False)
		post.post_owner=request.user
		post.save()
		return redirect("debate:index")
	context = {
		"form": form,'all_categories':all_categories
	}
	return render(request, 'debate/post_form.html', context)

class UpdatePost(UserPassesTestMixin,UpdateView):#LoginRequiredMixin,UserPassesTestMixin,UpdateView):#,UserPassesTestMixin,PermMixin,PermissionRequiredMixin
	model=Post
	# fields='__all__'
	fields=['post_topic','post_category','post_content']
	def test_func(self):
		post=self.get_object()
		print ("self.request.user.is_superuser :",self.request.user.is_superuser)
		print ("self.request.user :",self.request.user)
		print ("post.post_owner :",post.post_owner)
		print ("self.request.user == post.post_owner :",self.request.user == post.post_owner)
		if self.request.user == post.post_owner :
			return True
		else:
			messages.error(self.request,"User must be owner of this post to update")
			return False
			return redirect("debate:detail",pk=post.id)

def DeletePost(request, pk):
	post = Post.objects.get(id=pk)
	if request.user == post.post_owner:
		post.delete()
		return redirect('debate:index')

	else:
		messages.error(request,"User must be owner of this post to delete")
		return redirect("debate:detail",pk=pk)

@login_required(login_url='rap:login_user')
def delete_comment(request,pk,com_id):
	comment = Comment.objects.get(pk=com_id)
	com_name=Comment.objects.get(pk=com_id).comment_name
	print ("com_name :",com_name)
	print("request.user.username :",request.user.username)
	print("com_name == request.user.username :",com_name == request.user)
	if com_name == request.user: #or request.user.is_superuser:
		comment.delete()
		messages.success(request,"Comment deleted successfully")
		return redirect('debate:detail',pk=pk)
	else:
		messages.error(request,"User must be owner of this comment to delete")

src/debate_website/debate/templates/debate/add_comment.html
{% extends 'debate/base.html' %}
{% block title %} Add Comment {% endblock %}
{% block comments %}active{% endblock %}
{% block body %}
<div class="col-md-10 col-md-offset-1 col-sm-12" style="background: white;padding-top: 10px">
    <div>
        {% if not user.is_active %}
            <a href="{% url 'debate:add-comment'%}" style="padding-top: 10px;">Login to add comments.</a>
        {% endif %}
        <form action="." method="post" enctype="multipart/form-data"  style="padding-top: 10px;">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Post comment" class="btn btn-default">
        </form>
        <hr/>
        <p class="lead">{{ all_comments.count }} Comments</p>
        {% for com in all_comments %}
        <blockquote>
            <p style="display: inline">{{ com.comment_text}}</p>
            {% if user.is_superuser %}
                <a href="{% url 'debate:delete-comment' com.id %}" style="display: inline;">Delete</a>
            {% endif %}
            <br>
            <h6 class="text-muted" style="display: inline">{{ com.comment_name }}, posted {{ com.comment_time|timesince }} ago{% if com.children.count > 0 %} | {{ com.children.count }} Comment{% if com.children.count > 1%}s{% endif %}{% endif %}</h6>
            <!-- <a class="comment-reply-btn" href="#">Reply</a></h6> -->
            <br>
            <div class='comment-reply'>
                {% for reply in com.children %}

                    <blockquote>
                        <p style="display: inline">{{ reply.comment_text}}</p>
                        {% if user.is_superuser %}
                            <a href="{% url 'debate:delete-comment' reply.id %}" style="display: inline;">Delete</a>
                        {% endif %}
                        <h6 class="text-muted">{{ reply.comment_name }}, posted {{ reply.comment_time|timesince }} ago.</h6>
                    </blockquote>
                {% endfor %}

                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form}}
                    <!-- <input type="hidden" name="next" value="{{ request.GET.next }}"> -->
                    <input type="hidden" name="parent_id" value="{{ com.id }}">
                    <input type="submit" value="Reply" class="btn btn-default">
                </form>
            </div>
        </blockquote>
        <hr/>

        {% endfor %}
    </div>
</div>

{% endblock %}

src/debate_website/debate/templates/debate/base.html
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Speak Up{% endblock %}</title>
    {% load staticfiles %}

    <script src="{% static 'debate/bootstrap-3.3.7-dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'debate/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'debate/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />
    <link href="{% static 'debate/Satisfy.css' %}" rel="stylesheet" type="text/css">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'debate/style.css' %}" /> -->
    <link rel="icon" type="image/png" href="{% static 'debate/images/mic1.png' %}" />
    <script type="text/javascript">
    console.log("anil-out")
    $(".comment-reply-btn").click(function(event){
        // console.log("anil")
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })
    // console.log((document.getElementById("myLI").parentElement.nodeName))
    </script>

    <script type="text/javascript">
        $(document).on('click', '.confirm-delete', function(){
        return confirm('Are you sure you want to delete this?');
        })
    </script>
    <script type="text/javascript">
    console.log("Deletion")
    function ConfirmDelete()
        {
            var x = confirm("Are you sure you want to delete?");
            if (x){
                console.log(x)
                console.log("Deleted")
                // var a = this.getAttribute('href');
                // console.log(a)
                return true;
                    }else{
                        console.log(x)
                        console.log("else")
                        return false;
                         }
        }
    
    console.log("HREF")
    function myFunction() {
      var x = document.getElementById("deleteUpload").href;
      console.log(x)
      document.getElementById("demo").innerHTML = x;
    }
    </script>

</head>
<body>
<nav class="navbar navbar-inverse" style="border-radius:0px">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="active navbar-brand" href="{% url 'debate:index' %}"style="font-family: Satisfy">Speak Up</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Category
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for c in all_categories %}
                            <li><a href="{% url 'debate:categories' c.id %}">{{ c.name }}</a></li>
                            <!-- {% if user.is_superuser %}{{ c.id }}{% endif %}</a></li> -->
                        {% endfor %}
                    </ul>
                </li>
                {% if user.is_authenticated %}
                    <li class="{% block my_posts %}{% endblock %}"><a href="{% url 'debate:my_posts' user.id %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; My Posts</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="{% block add_posts %}{% endblock %}"><a href="{% url 'debate:post-create' %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Add Topics</a></li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="{% block add_category %}{% endblock %}"><a href="{% url 'debate:category-create' %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Add Category</a></li>
                {% endif %}
                <!-- <li class="{% block artist_details %}{% endblock %}"><a href="{% url 'debate:index' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Categories</a></li> -->
            </ul>
            {% comment %}
                <!-- {% if user.is_superuser %}     
                <li class="{% block add_artists %}{% endblock %}"><a href="{% url 'rap:artist-add' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;&nbsp;Add Artist</a></li>
                {% endif %}
                <li class="{% block all_songs %}{% endblock %}"><a href="{% url 'rap:all_songs' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; All Songs</a></li> -->
                <!-- <li class="{% block news %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp;&nbsp;News</a></li> -->
                <!-- <li class="{% block events %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp;&nbsp;Events</a></li> -->
                <!-- <li class="{% block comments %}{% endblock %}"><a href="{% url 'rap:comments' %}"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp;&nbsp;Comments</a></li> -->
                <!-- <li class="{% block fbcomments %}{% endblock %}"><a href="{% url 'rap:fb-comments' %}"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp;&nbsp;FB Comments</a></li> -->
                <!-- {% if user.is_superuser %}  
                <li class="{% block uploads %}{% endblock %}"><a href="{% url 'rap:all_uploads' %}"><span class="glyphicon glyphicon-cloud-upload" aria-hidden="true"></span>&nbsp;&nbsp;Uploads</a></li>
                {% endif %}
                <li class="{% block about %}{% endblock %}"><a href="{% url 'rap:about' %}"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp;&nbsp;About Us</a></li> -->
            </ul>

            action="{% url 'rap:index' %}"

            {% endcomment %}

            <form class="navbar-form navbar-right" action="{% url 'debate:index' %}" role="search" method="get" >
                <div class="form-group">
                    <input type="text" placeholder="Search" class="search form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </form>
            
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right"> 
                <li>
                    <a href="{% url 'debate:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
            {% endif %}

            <ul class="nav navbar-nav navbar-right">
                <li class="{% block log %}{% endblock %}">
                    {% if not user.is_authenticated %}
                    <a href="{% url 'debate:login_user' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login 
                    </a>
                    {% else %}
                    <a href="#">
                        <span class="glyphicon glyphicon-log-in"></span>&nbsp; Logged in as {{ request.user }}
                    </a>
                    {% endif %}

                </li>
            </ul>
        </div>
    </div>
</nav>
{% comment %}

<!-- <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="logoutModalLabel">Are you sure you want to logout ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" style="display: inline">Close</button>
                <form action="{% url 'rap:logout_user' %}" method="POST" style="display: inline">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Logout">
                </form>
            </div>
        </div>
    </div>
</div> -->
<!-- <div>
{% if messages %}
    {% for message in messages %}
        <div class="col-md-10 col-md-offset-1 col-sm-12" >
            <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}
</div> -->
{% endcomment %}
{% block body %}
{% endblock %}
</div>
<br>
<br>
</body>
</html>

src/debate_website/debate/templates/debate/form-template.html
{% if messages %}
    {% for message in messages %}
        <div class="col-md-10 col-md-offset-1 col-sm-12" >
            <!-- {{ message.tags }} -->
            <div class="alert alert-{% if 'error' in message.tags %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade in" role="alert" style="text-align: center">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ message }}</strong>
            </div>
        </div>
    {% endfor %}
{% endif %}
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
       <span class="text-danger small">{{ field.errors }}</span>  
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
      <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}